# Generated by Django 5.0.2 on 2024-03-01 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.IntegerField(verbose_name='消費税率')),
                ('activation_date', models.DateField(verbose_name='有効日')),
                ('expiration_date', models.DateField(null=True, verbose_name='失効日')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='商品名')),
                ('price', models.PositiveIntegerField(verbose_name='価格')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='売上金額')),
                ('sales_date', models.DateTimeField(auto_now_add=True, verbose_name='売上日')),
                ('delivery_status', models.CharField(choices=[('ORDERING', '発注中'), ('DELIVERED', '発送済み')], default='ORDERING', verbose_name='配送状態')),
                ('consumption_tax', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='chapter_2.consumptiontax')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('buyer', models.CharField(max_length=255, verbose_name='購入者')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='chapter_2.product')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='chapter_2.sales')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
    ]
