# Generated by Django 5.0.2 on 2024-03-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_2', '0002_alter_expiration_date_null_constraints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
    ]
