# Generated by Django 5.0.2 on 2024-02-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_1', '0001_add_bad_hoge_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodHoge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
            ],
            options={
                'db_table': 'good_hoge',
            },
        ),
    ]
